data:
  image: python:3.6
  volumes:
    - ./:/app
    - ./data:/data

import:
  build: .
  volumes_from:
    - data
  environment:
    - GNAF_DUMP_URL=$GNAF_DUMP_URL
    - ADMIN_BDYS_DUMP_URL=$ADMIN_BDYS_DUMP_URL
    - PGHOST=$RDS_ENDPOINT
    - PGPORT=$RDS_ENDPOINT_PORT
    - PGDATABASE=$RDS_DB_NAME
    - PGUSER=$RDS_DB_USER
    - PGPASSWORD=$RDS_DB_PWD