version: 0.2

env:
  git-credential-helper: yes
  variables:
    GITHUB_USERNAME: energetiq-codebuild

phases:
  pre_build:
    commands:
      - mkdir ./ops/data
  build:
    commands:
      - cd ./ops
      - docker-compose up