version: 0.2

env:
  git-credential-helper: yes
  variables:
    GITHUB_USERNAME: energetiq-codebuild

phases:
  install:
    runtime-versions:
      python: 3.7
  pre_build:
    commands:
      - mkdir ./data
      - chmod +x ./download.sh
      - chmod +x ./install.sh
  build:
    commands:
      - ./download.sh
      - ./install.sh
      - PGPASSWORD=postgres psql -h db -d geo -p 5432 -U postgres -l