AWSTemplateFormatVersion: 2010-09-09

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
  VpcSecurityGroupIds:
    Type: List<AWS::EC2::SecurityGroup::Id>
  VpcSubnetIds:
    Type: List<AWS::EC2::Subnet::Id>

Resources:
  NmiGeolocationGNAFLoader:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: NO_ARTIFACTS
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:3.0
        Type: LINUX_CONTAINER
        PrivilegedMode: true
        EnvironmentVariables:
          - Name: GNAF_DUMP_URL
            Type: PLAINTEXT
            Value: http://minus34.com/opendata/psma-202005/gnaf-202005.dmp
          - Name: ADMIN_BDYS_DUMP_URL
            Type: PLAINTEXT
            Value: ""
          - Name: RDS_ENDPOINT
            Type: SECRETS_MANAGER
            Value: "/:host"
          - Name: RDS_ENDPOINT_PORT
            Type: SECRETS_MANAGER
            Value: "/:port"
          - Name: RDS_DB_NAME
            Type: SECRETS_MANAGER
            Value: "/:dbname"
          - Name: RDS_DB_USER
            Type: SECRETS_MANAGER
            Value: "/:username"
          - Name: RDS_DB_PWD
            Type: SECRETS_MANAGER
            Value: "/:password"
      Name: nmi-geolocation-gnaf-loader
      Description: "Import GNAF loader pg dumps to nmi-geolocation RDS instance"
      QueuedTimeoutInMinutes: 60
      ServiceRole: !Sub arn:aws:iam::${AWS::AccountId}:role/service-role/codebuild
      Source:
        Type: GITHUB
        GitCloneDepth: 1
        Location: https://github.com/shinetech/gnaf-loader.git
        BuildSpec: ops/loader.buildspec.yml
      SourceVersion: master
      TimeoutInMinutes: 300
      VpcConfig:
        SecurityGroupIds: !Ref VpcSecurityGroupIds
        Subnets: !Ref VpcSubnetIds
        VpcId: !Ref VpcId