AWSTemplateFormatVersion: 2010-09-09

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
  VpcSecurityGroupIds:
    Type: List<AWS::EC2::SecurityGroup::Id>
  VpcSubnetIds:
    Type: List<AWS::EC2::Subnet::Id>

Resources:
  NmiGeolocationGNAFLoader:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: NO_ARTIFACTS
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:3.0
        Type: LINUX_CONTAINER
        PrivilegedMode: true
        EnvironmentVariables:
          - Name: GNAF_DUMP_URL
            Type: PLAINTEXT
            Value: http://minus34.com/opendata/psma-202005/gnaf-202005.dmp
          - Name: ADMIN_BDYS_DUMP_URL
            Type: PLAINTEXT
          - Name: RDS_ENDPOINT
            Type: PLAINTEXT
            Value: nmi-geolocation-geo-test.c3ofafl582h0.ap-southeast-2.rds.amazonaws.com
          - Name: RDS_ENDPOINT_PORT
            Type: PLAINTEXT
            Value: 5432
          - Name: RDS_DB_NAME
            Type: PLAINTEXT
            Value: geo
          - Name: RDS_DB_USER
            Type: PLAINTEXT
            Value: postgres
          - Name: RDS_DB_PWD
            Type: PLAINTEXT
      Name: nmi-geolocation-gnaf-loader
      Description: "Run GNAF loader to generate pg dumps and import to nmi-geolocation db instance"
      QueuedTimeoutInMinutes: 60
      ServiceRole: !Sub arn:aws:iam::${AWS::AccountId}:role/service-role/codebuild
      Source:
        Type: GITHUB
        GitCloneDepth: 1
        Location: https://github.com/shinetech/gnaf-loader.git
        BuildSpec: ops/loader.buildspec.yml
      SourceVersion: refs/pull/1/head
      TimeoutInMinutes: 300
      VpcConfig:
        SecurityGroupIds: !Ref VpcSecurityGroupIds
        Subnets: !Ref VpcSubnetIds
        VpcId: !Ref VpcId