AWSTemplateFormatVersion: 2010-09-09

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
  VpcSecurityGroupIds:
    Type: List<AWS::EC2::SecurityGroup::Id>
  VpcSubnetIds:
    Type: List<AWS::EC2::Subnet::Id>

Resources:
  NmiGeolocationGNAFLoader:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: NO_ARTIFACTS
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:3.0
        Type: LINUX_CONTAINER
        PrivilegedMode: true
        EnvironmentVariables:
          - Name: GNAF_DOWNLOAD_URL
            Type: PLAINTEXT
            Value: https://data.gov.au/data/dataset/19432f89-dc3a-4ef3-b943-5326ef1dbecc/resource/4b084096-65e4-4c8e-abbe-5e54ff85f42f/download/may20_gnaf_pipeseparatedvalue.zip
          - Name: ADMIN_BDYS_DOWNLOAD_URL
            Type: PLAINTEXT
            Value: https://data.gov.au/data/dataset/bdcf5b09-89bc-47ec-9281-6b8e9ee147aa/resource/53c24b8e-4f55-4eed-a189-2fc0dcca6381/download/may20_adminbounds_esrishapefileordbffile.zip
          - Name: RDS_ENDPOINT
            Type: PLAINTEXT
            Value: nmi-geolocation-geo-test.c3ofafl582h0.ap-southeast-2.rds.amazonaws.com
          - Name: RDS_ENDPOINT_PORT
            Type: PLAINTEXT
            Value: 5432
          - Name: RDS_DB_NAME
            Type: PLAINTEXT
            Value: geo
          - Name: RDS_DB_USER
            Type: PLAINTEXT
            Value: postgres
          - Name: RDS_DB_PWD
            Type: PLAINTEXT
            Value: postgres
      Name: nmi-geolocation-gnaf-loader
      Description: "Run GNAF loader to generate pg dumps and import to nmi-geolocation db instance"
      QueuedTimeoutInMinutes: 60
      ServiceRole: !Sub arn:aws:iam::${AWS::AccountId}:role/service-role/codebuild
      Source:
        Type: GITHUB
        GitCloneDepth: 1
        Location: https://github.com/shinetech/gnaf-loader.git
        BuildSpec: ops/loader.buildspec.yml
      SourceVersion: refs/pull/1/head
      TimeoutInMinutes: 300
      VpcConfig:
        SecurityGroupIds: !Ref VpcSecurityGroupIds
        Subnets: !Ref VpcSubnetIds
        VpcId: !Ref VpcId